expressions:
  - name: get-faidx-file-from-reference-file
    path: get-faidx-file-from-reference-file
    versions:
      - name: 1.0.0
        path: 1.0.0/get-faidx-file-from-reference-file__1.0.0.cwl
        md5sum: 5537a7433792c92e63c11abe20e9ba78
    categories: []
  - name: create-contig-obj-for-hla-chr6-region
    path: create-contig-obj-for-hla-chr6-region
    versions:
      - name: 1.0.0
        path: 1.0.0/create-contig-obj-for-hla-chr6-region__1.0.0.cwl
        md5sum: a592eeffe3208dcd7d12bdbda11e4e65
    categories: []
  - name: get-samplesheet-midfix-regex
    path: get-samplesheet-midfix-regex
    versions:
      - name: 1.0.0
        path: 1.0.0/get-samplesheet-midfix-regex__1.0.0.cwl
        md5sum: 93d9dba10e7674e53a886ef28818c133
    categories: []
  - name: flatten-array-fastq-list
    path: flatten-array-fastq-list
    versions:
      - name: 1.0.0
        path: 1.0.0/flatten-array-fastq-list__1.0.0.cwl
        md5sum: 3fd2377b47c3641f64e43b530138ae02
    categories: []
  - name: parse-int-array
    path: parse-int-array
    versions:
      - name: 1.0.0
        path: 1.0.0/parse-int-array__1.0.0.cwl
        md5sum: 910b29813ea555a3ac2bd45779cb9a47
    categories: []
  - name: parse-int
    path: parse-int
    versions:
      - name: 1.0.0
        path: 1.0.0/parse-int__1.0.0.cwl
        md5sum: 09a91ad5503a72e12b484f12f9e958ac
    categories: []
  - name: parse-file
    path: parse-file
    versions:
      - name: 1.0.0
        path: 1.0.0/parse-file__1.0.0.cwl
        md5sum: 36ec6774ad49393e036502ef632ea711
    categories: []
