projects:
  - project_name: development
    project_id: dc8e6ba9-b744-437b-b070-4cf014694b3d
    project_description: |
        Development project
    project_abbr: dev
    project_api_key_name: development
    production: false
    tenant_id: YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ
    tools:
      - name: samtools-merge
        path: samtools-merge
        ica_workflow_name: samtools-merge_dev
        ica_workflow_id: wfl.a717e4b2ec484c4cab2910c813179738
        versions:
          - name: 1.12.0
            path: 1.12.0/samtools-merge__1.12.0.cwl
            ica_workflow_version_name: 1.12.0
            modification_time: 2021-05-12T08:12:40UTC
            run_instances: []
      - name: tabix
        path: tabix
        ica_workflow_name: tabix_dev
        ica_workflow_id: wfl.e75e5b7c2981407db574f5e0e4b07a0d
        versions:
          - name: 0.2.6
            path: 0.2.6/tabix__0.2.6.cwl
            ica_workflow_version_name: 0.2.6
            modification_time: 2021-05-19T08:03:27UTC
            run_instances: []
      - name: sambamba-merge-and-index
        path: sambamba-merge-and-index
        ica_workflow_name: sambamba-merge-and-index_dev
        ica_workflow_id: wfl.84d02a51ca1e4f4091a18ab73b1d3f73
        versions:
          - name: 0.8.0
            path: 0.8.0/sambamba-merge-and-index__0.8.0.cwl
            ica_workflow_version_name: 0.8.0
            modification_time: 2021-05-20T04:39:10UTC
            run_instances: []
      - name: sambamba-sort-and-index
        path: sambamba-sort-and-index
        ica_workflow_name: sambamba-sort-and-index_dev
        ica_workflow_id: wfl.68849cc2a7094f87abbd6e8483169bc2
        versions:
          - name: 0.8.0
            path: 0.8.0/sambamba-sort-and-index__0.8.0.cwl
            ica_workflow_version_name: 0.8.0
            modification_time: 2021-05-20T04:40:53UTC
            run_instances: []
      - name: sambamba-slice-and-index
        path: sambamba-slice-and-index
        ica_workflow_name: sambamba-slice-and-index_dev
        ica_workflow_id: wfl.591b79cb43d0492380e3039ed5c517c0
        versions:
          - name: 0.8.0
            path: 0.8.0/sambamba-slice-and-index__0.8.0.cwl
            ica_workflow_version_name: 0.8.0
            modification_time: 2021-05-20T04:41:25UTC
            run_instances: []
      - name: sambamba-view-and-index
        path: sambamba-view-and-index
        ica_workflow_name: sambamba-view-and-index_dev
        ica_workflow_id: wfl.6304aa7f0fcb4a97a29ab27262383281
        versions:
          - name: 0.8.0
            path: 0.8.0/sambamba-view-and-index__0.8.0.cwl
            ica_workflow_version_name: 0.8.0
            modification_time: 2021-05-20T04:41:57UTC
            run_instances: []
      - name: optitype
        path: optitype
        ica_workflow_name: optitype_dev
        ica_workflow_id: wfl.7747fed243b4422eb1c40cb1fa9fea75
        versions:
          - name: 1.3.5
            path: 1.3.5/optitype__1.3.5.cwl
            ica_workflow_version_name: 1.3.5
            modification_time: 2021-05-21T05:02:19UTC
            run_instances: []
      - name: custom-subset-bam
        path: custom-subset-bam
        ica_workflow_name: custom-subset-bam_dev
        ica_workflow_id: wfl.18ab0d900ea0453384db086a4fbc5ed9
        versions:
          - name: 1.12.0
            path: 1.12.0/custom-subset-bam__1.12.0.cwl
            ica_workflow_version_name: 1.12.0
            modification_time: 2021-05-20T04:53:30UTC
            run_instances: []
      - name: bedops
        path: bedops
        ica_workflow_name: bedops_dev
        ica_workflow_id: wfl.5808cc6b5c6b4386b1ad966fabcec1be
        versions:
          - name: 2.4.39
            path: 2.4.39/bedops__2.4.39.cwl
            ica_workflow_version_name: 2.4.39
            modification_time: 2021-05-21T00:21:30UTC
            run_instances: []
      - name: dragen-germline
        path: dragen-germline
        ica_workflow_name: dragen-germline_dev
        ica_workflow_id: wfl.a19f90ebde874ceba9f3f41f82878e8c
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-germline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-05-21T08:25:18UTC
            run_instances: []
    workflows:
      - name: optitype-pipeline
        path: optitype-pipeline
        ica_workflow_name: optitype-pipeline_dev
        ica_workflow_id: wfl.e1332fc391564d93bfba7e206ab0ab3e
        versions:
          - name: 1.3.5
            path: 1.3.5/optitype-pipeline__1.3.5.cwl
            ica_workflow_version_name: 1.3.5
            modification_time: 2021-05-20T04:48:01UTC
            run_instances: []
      - name: get-hla-regions-bed
        path: get-hla-regions-bed
        ica_workflow_name: get-hla-regions-bed_dev
        ica_workflow_id: wfl.4c8ce85b9d2f427bb08e288d0e915981
        versions:
          - name: 1.0.0
            path: 1.0.0/get-hla-regions-bed__1.0.0.cwl
            ica_workflow_version_name: 1.0.0
            modification_time: 2021-05-21T02:29:48UTC
            run_instances: []
      - name: dragen-germline-pipeline
        path: dragen-germline-pipeline
        ica_workflow_name: dragen-germline-pipeline_dev
        ica_workflow_id: wfl.c5b3bd16ef014a338d489b6829d685c6
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-germline-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-05-21T08:33:58UTC
            run_instances: []
      - name: dragen-qc-hla-pipeline
        path: dragen-qc-hla-pipeline
        ica_workflow_name: dragen-qc-hla-pipeline_dev
        ica_workflow_id: wfl.31d0e45ea17443f18768386f16b82af8
        versions:
          - name: 3.7.5--1.3.5
            path: 3.7.5--1.3.5/dragen-qc-hla-pipeline__3.7.5--1.3.5.cwl
            ica_workflow_version_name: 3.7.5--1.3.5
            modification_time: 2021-05-21T08:52:39UTC
            run_instances: []
