projects:
  - project_name: development_workflows
    project_id: 0df0356d-3637-48a5-80d1-a924642a6556
    project_description: |
        Development workflows, project is linked to the development
        project
    project_abbr: dev-wf
    project_api_key_name: development_workflows
    production: false
    linked_projects:
      - dc8e6ba9-b744-437b-b070-4cf014694b3d
    tenant_id: YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ
    tools:
      - name: samtools-merge
        path: samtools-merge
        ica_workflow_name: samtools-merge_dev-wf
        ica_workflow_id: wfl.a717e4b2ec484c4cab2910c813179738
        versions:
          - name: 1.12.0
            path: 1.12.0/samtools-merge__1.12.0.cwl
            ica_workflow_version_name: 1.12.0
            modification_time: 2021-06-25T02:25:00UTC
            run_instances: []
      - name: tabix
        path: tabix
        ica_workflow_name: tabix_dev-wf
        ica_workflow_id: wfl.e75e5b7c2981407db574f5e0e4b07a0d
        versions:
          - name: 0.2.6
            path: 0.2.6/tabix__0.2.6.cwl
            ica_workflow_version_name: 0.2.6
            modification_time: 2021-06-25T02:25:01UTC
            run_instances: []
      - name: sambamba-merge-and-index
        path: sambamba-merge-and-index
        ica_workflow_name: sambamba-merge-and-index_dev-wf
        ica_workflow_id: wfl.84d02a51ca1e4f4091a18ab73b1d3f73
        versions:
          - name: 0.8.0
            path: 0.8.0/sambamba-merge-and-index__0.8.0.cwl
            ica_workflow_version_name: 0.8.0
            modification_time: 2021-06-25T02:25:01UTC
            run_instances: []
      - name: sambamba-sort-and-index
        path: sambamba-sort-and-index
        ica_workflow_name: sambamba-sort-and-index_dev-wf
        ica_workflow_id: wfl.68849cc2a7094f87abbd6e8483169bc2
        versions:
          - name: 0.8.0
            path: 0.8.0/sambamba-sort-and-index__0.8.0.cwl
            ica_workflow_version_name: 0.8.0
            modification_time: 2021-06-25T02:25:02UTC
            run_instances: []
      - name: sambamba-slice-and-index
        path: sambamba-slice-and-index
        ica_workflow_name: sambamba-slice-and-index_dev-wf
        ica_workflow_id: wfl.591b79cb43d0492380e3039ed5c517c0
        versions:
          - name: 0.8.0
            path: 0.8.0/sambamba-slice-and-index__0.8.0.cwl
            ica_workflow_version_name: 0.8.0
            modification_time: 2021-06-25T02:25:02UTC
            run_instances: []
      - name: sambamba-view-and-index
        path: sambamba-view-and-index
        ica_workflow_name: sambamba-view-and-index_dev-wf
        ica_workflow_id: wfl.6304aa7f0fcb4a97a29ab27262383281
        versions:
          - name: 0.8.0
            path: 0.8.0/sambamba-view-and-index__0.8.0.cwl
            ica_workflow_version_name: 0.8.0
            modification_time: 2021-06-25T02:25:02UTC
            run_instances: []
      - name: optitype
        path: optitype
        ica_workflow_name: optitype_dev-wf
        ica_workflow_id: wfl.7747fed243b4422eb1c40cb1fa9fea75
        versions:
          - name: 1.3.5
            path: 1.3.5/optitype__1.3.5.cwl
            ica_workflow_version_name: 1.3.5
            modification_time: 2021-06-25T02:25:03UTC
            run_instances: []
      - name: custom-subset-bam
        path: custom-subset-bam
        ica_workflow_name: custom-subset-bam_dev-wf
        ica_workflow_id: wfl.18ab0d900ea0453384db086a4fbc5ed9
        versions:
          - name: 1.12.0
            path: 1.12.0/custom-subset-bam__1.12.0.cwl
            ica_workflow_version_name: 1.12.0
            modification_time: 2021-06-25T02:25:03UTC
            run_instances: []
      - name: bedops
        path: bedops
        ica_workflow_name: bedops_dev-wf
        ica_workflow_id: wfl.5808cc6b5c6b4386b1ad966fabcec1be
        versions:
          - name: 2.4.39
            path: 2.4.39/bedops__2.4.39.cwl
            ica_workflow_version_name: 2.4.39
            modification_time: 2021-06-25T02:25:04UTC
            run_instances: []
      - name: dragen-germline
        path: dragen-germline
        ica_workflow_name: dragen-germline_dev-wf
        ica_workflow_id: wfl.a19f90ebde874ceba9f3f41f82878e8c
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-germline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-06-29T00:51:41UTC
            run_instances: []
      - name: custom-create-tso500-samplesheet
        path: custom-create-tso500-samplesheet
        ica_workflow_name: custom-create-tso500-samplesheet_dev-wf
        ica_workflow_id: wfl.a754b24fde75444b8e97f67412b935fe
        versions:
          - name: 1.0.0
            path: 1.0.0/custom-create-tso500-samplesheet__1.0.0.cwl
            ica_workflow_version_name: 1.0.0
            modification_time: 2021-06-25T02:25:05UTC
            run_instances: []
      - name: tso500-ctdna-demultiplex-workflow
        path: tso500-ctdna-demultiplex-workflow
        ica_workflow_name: tso500-ctdna-demultiplex-workflow_dev-wf
        ica_workflow_id: wfl.fd8c8ddabe824ae3a730aa2ce926785d
        versions:
          - name: 1.1.0--120
            path: 1.1.0--120/tso500-ctdna-demultiplex-workflow__1.1.0--120.cwl
            ica_workflow_version_name: 1.1.0--120
            modification_time: 2021-06-29T00:51:42UTC
            run_instances: []
      - name: tso500-ctdna-analysis-workflow
        path: tso500-ctdna-analysis-workflow
        ica_workflow_name: tso500-ctdna-analysis-workflow_dev-wf
        ica_workflow_id: wfl.867aabc177344a40ae61ef868ddd3c98
        versions:
          - name: 1.1.0--120
            path: 1.1.0--120/tso500-ctdna-analysis-workflow__1.1.0--120.cwl
            ica_workflow_version_name: 1.1.0--120
            modification_time: 2021-06-29T00:51:42UTC
            run_instances: []
      - name: tso500-ctdna-reporting-workflow
        path: tso500-ctdna-reporting-workflow
        ica_workflow_name: tso500-ctdna-reporting-workflow_dev-wf
        ica_workflow_id: wfl.5a87e61d60234647b282368b1beaa396
        versions:
          - name: 1.1.0--120
            path: 1.1.0--120/tso500-ctdna-reporting-workflow__1.1.0--120.cwl
            ica_workflow_version_name: 1.1.0--120
            modification_time: 2021-06-29T00:51:43UTC
            run_instances: []
      - name: multiqc
        path: multiqc
        ica_workflow_name: multiqc_dev-wf
        ica_workflow_id: wfl.c2ca973c62a24066bf82f63715d66083
        versions:
          - name: 1.10.1
            path: 1.10.1/multiqc__1.10.1.cwl
            ica_workflow_version_name: 1.10.1
            modification_time: 2021-06-29T00:51:43UTC
            run_instances: []
      - name: dragen-alignment
        path: dragen-alignment
        ica_workflow_name: dragen-alignment_dev-wf
        ica_workflow_id: wfl.b2b0f4d467df453abd5526eb73b3afb7
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-alignment__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-06-29T00:51:44UTC
            run_instances: []
      - name: arriba-drawing
        path: arriba-drawing
        ica_workflow_name: arriba-drawing_dev-wf
        ica_workflow_id: wfl.7620a30e5df3446091c73d3fa10db084
        versions:
          - name: 2.0.0
            path: 2.0.0/arriba-drawing__2.0.0.cwl
            ica_workflow_version_name: 2.0.0
            modification_time: 2021-06-29T01:01:43UTC
            run_instances: []
      - name: custom-create-directory
        path: custom-create-directory
        ica_workflow_name: custom-create-directory_dev-wf
        ica_workflow_id: wfl.d58562105cb74b67906be002c2f53bef
        versions:
          - name: 1.0.0
            path: 1.0.0/custom-create-directory__1.0.0.cwl
            ica_workflow_version_name: 1.0.0
            modification_time: 2021-06-30T07:00:07UTC
            run_instances: []
    workflows:
      - name: optitype-pipeline
        path: optitype-pipeline
        ica_workflow_name: optitype-pipeline_dev-wf
        ica_workflow_id: wfl.e1332fc391564d93bfba7e206ab0ab3e
        versions:
          - name: 1.3.5
            path: 1.3.5/optitype-pipeline__1.3.5.cwl
            ica_workflow_version_name: 1.3.5
            modification_time: 2021-06-28T02:34:52UTC
            run_instances: []
      - name: get-hla-regions-bed
        path: get-hla-regions-bed
        ica_workflow_name: get-hla-regions-bed_dev-wf
        ica_workflow_id: wfl.4c8ce85b9d2f427bb08e288d0e915981
        versions:
          - name: 1.0.0
            path: 1.0.0/get-hla-regions-bed__1.0.0.cwl
            ica_workflow_version_name: 1.0.0
            modification_time: 2021-06-29T01:55:56UTC
            run_instances: []
      - name: dragen-germline-pipeline
        path: dragen-germline-pipeline
        ica_workflow_name: dragen-germline-pipeline_dev-wf
        ica_workflow_id: wfl.c5b3bd16ef014a338d489b6829d685c6
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-germline-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-07-01T03:33:50UTC
            run_instances: []
      - name: dragen-qc-hla-pipeline
        path: dragen-qc-hla-pipeline
        ica_workflow_name: dragen-qc-hla-pipeline_dev-wf
        ica_workflow_id: wfl.31d0e45ea17443f18768386f16b82af8
        versions:
          - name: 3.7.5--1.3.5
            path: 3.7.5--1.3.5/dragen-qc-hla-pipeline__3.7.5--1.3.5.cwl
            ica_workflow_version_name: 3.7.5--1.3.5
            modification_time: 2021-07-01T03:55:15UTC
            run_instances: []
      - name: tso500-ctdna
        path: tso500-ctdna
        ica_workflow_name: tso500-ctdna_dev-wf
        ica_workflow_id: wfl.3cfe22e0ca1f43a8b68c1ec820a0a5dc
        versions:
          - name: 1.1.0--120
            path: 1.1.0--120/tso500-ctdna__1.1.0--120.cwl
            ica_workflow_version_name: 1.1.0--120
            modification_time: 2021-06-29T01:56:00UTC
            run_instances: []
      - name: dragen-somatic-pipeline
        path: dragen-somatic-pipeline
        ica_workflow_name: dragen-somatic-pipeline_dev-wf
        ica_workflow_id: wfl.32e346cdbb854f6487e7594ec17a81f9
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-somatic-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-07-01T03:35:13UTC
            run_instances: []
      - name: bcl-conversion
        path: bcl-conversion
        ica_workflow_name: bcl-conversion_dev-wf
        ica_workflow_id: wfl.59e481580c6243b6b237ca2b08fa1270
        versions:
          - name: 3.7.5
            path: 3.7.5/bcl-conversion__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-06-29T01:56:01UTC
            run_instances: []
      - name: dragen-transcriptome-pipeline
        path: dragen-transcriptome-pipeline
        ica_workflow_name: dragen-transcriptome-pipeline_dev-wf
        ica_workflow_id: wfl.286d4a2e82f048609d5b288a9d2868f6
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-transcriptome-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-07-02T12:18:34UTC
            run_instances: []
      - name: dragen-alignment-pipeline
        path: dragen-alignment-pipeline
        ica_workflow_name: dragen-alignment-pipeline_dev-wf
        ica_workflow_id: wfl.a3e19e590ed34a0fa0518718cb8a36cf
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-alignment-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-07-02T05:02:42UTC
            run_instances: []
      - name: dragen-wgs-qc-pipeline
        path: dragen-wgs-qc-pipeline
        ica_workflow_name: dragen-wgs-qc-pipeline_dev-wf
        ica_workflow_id: wfl.ff6ca1789f4e4eb0982ea3e01407aca8
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-wgs-qc-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5
            modification_time: 2021-07-02T05:02:49UTC
            run_instances: []
  - project_name: production_workflows
    project_id: fdd48e11-cdcc-46a9-b5ac-dee3a4c5f19d
    project_description: |
        Production workflows, project is linked to the production
        project
    project_abbr: prod-wf
    project_api_key_name: production_workflows
    production: true
    linked_projects:
      - 20b42a71-1ebc-4e7b-b659-313f2f4524c3
    tenant_id: YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ
    tools: []
    workflows:
      - name: tso500-ctdna
        path: tso500-ctdna
        ica_workflow_name: tso500-ctdna_prod-wf
        ica_workflow_id: wfl.576020a89adb49c3b2081a620d19104d
        versions:
          - name: 1.1.0--120
            path: 1.1.0--120/tso500-ctdna__1.1.0--120.cwl
            ica_workflow_version_name: 1.1.0--120--ef43134
            modification_time: 2021-06-29T01:56:03UTC
            run_instances: []
      - name: dragen-somatic-pipeline
        path: dragen-somatic-pipeline
        ica_workflow_name: dragen-somatic-pipeline_prod-wf
        ica_workflow_id: wfl.aa0ccece4e004839aa7374d1d6530633
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-somatic-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5--ef43134
            modification_time: 2021-06-29T01:56:03UTC
            run_instances: []
          - name: 3.7.5
            path: 3.7.5/dragen-somatic-pipeline__3.7.5cwl
            ica_workflow_version_name: 3.7.5--29dfde0
            modification_time: 2021-07-01T03:55:38UTC
            run_instances: []
      - name: bcl-conversion
        path: bcl-conversion
        ica_workflow_name: bcl-conversion_prod-wf
        ica_workflow_id: wfl.f257ca35ced94e648fdda1173144c476
        versions:
          - name: 3.7.5
            path: 3.7.5/bcl-conversion__3.7.5.cwl
            ica_workflow_version_name: 3.7.5--ef43134
            modification_time: 2021-06-29T01:56:04UTC
            run_instances: []
      - name: dragen-transcriptome-pipeline
        path: dragen-transcriptome-pipeline
        ica_workflow_name: dragen-transcriptome-pipeline_prod-wf
        ica_workflow_id: wfl.7e5ba7470b5549a6b4bf6d95daaa1214
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-transcriptome-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5--ef43134
            modification_time: 2021-06-29T01:56:04UTC
            run_instances: []
      - name: dragen-germline-pipeline
        path: dragen-germline-pipeline
        ica_workflow_name: dragen-germline-pipeline_prod-wf
        ica_workflow_id: wfl.b41302dd537d44fd92ae719a367d69fd
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-germline-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5--29dfde0
            modification_time: 2021-07-01T03:55:44UTC
            run_instances: []
      - name: dragen-wgs-qc-pipeline
        path: dragen-wgs-qc-pipeline
        ica_workflow_name: dragen-wgs-qc-pipeline_prod-wf
        ica_workflow_id: wfl.23f61cb1baab412a8c37dc93bed6c2af
        versions:
          - name: 3.7.5
            path: 3.7.5/dragen-wgs-qc-pipeline__3.7.5.cwl
            ica_workflow_version_name: 3.7.5--67a9d2b
            modification_time: 2021-07-02T05:02:57UTC
            run_instances: []
  - project_name: collab-illumina-dev_workflows
    project_id: dddd6c29-24d3-49f4-91c0-7e818b3c0a21
    project_description: |
        Repository Project containing tools and workflows for the
        collab-illumina-dev project
    project_abbr: clb-ilmn-dev_wf
    project_api_key_name: collab-illumina-dev_workflows
    production: false
    linked_projects:
      - 30f09dfb-10e3-43b4-9056-07c8623b96a3
    tenant_id: YXdzLXVzLXBsYXRmb3JtOjEwMDAwNTM3OjBiYTU5YWUxLWZkYWUtNDNiYS1hM2I1LTRkMzY3YTQzYWJkNQ
    tools:
      - name: custom-create-tso500-samplesheet
        path: custom-create-tso500-samplesheet
        ica_workflow_name: custom-create-tso500-samplesheet_clb-ilmn-dev
        ica_workflow_id: wfl.3d98d8f73eb4408084594a42fa227a89
        versions:
          - name: 1.0.0
            path: 1.0.0/custom-create-tso500-samplesheet__1.0.0.cwl
            ica_workflow_version_name: 1.0.0
            modification_time: 2021-06-29T04:56:05UTC
            run_instances: []
      - name: tso500-ctdna-demultiplex-workflow
        path: tso500-ctdna-demultiplex-workflow
        ica_workflow_name: tso500-ctdna-demultiplex-workflow_clb-ilmn-dev
        ica_workflow_id: wfl.0cf5fb870db44158876dd0849470f573
        versions:
          - name: 1.1.0--120
            path: 1.1.0--120/tso500-ctdna-demultiplex-workflow__1.1.0--120.cwl
            ica_workflow_version_name: 1.1.0--120
            modification_time: 2021-06-29T04:56:06UTC
            run_instances: []
      - name: tso500-ctdna-analysis-workflow
        path: tso500-ctdna-analysis-workflow
        ica_workflow_name: tso500-ctdna-analysis-workflow_clb-ilmn-dev
        ica_workflow_id: wfl.544d209e70d1470b93ef0033ba201784
        versions:
          - name: 1.1.0--120
            path: 1.1.0--120/tso500-ctdna-analysis-workflow__1.1.0--120.cwl
            ica_workflow_version_name: 1.1.0--120
            modification_time: 2021-06-29T04:56:06UTC
            run_instances: []
      - name: tso500-ctdna-reporting-workflow
        path: tso500-ctdna-reporting-workflow
        ica_workflow_name: tso500-ctdna-reporting-workflow_clb-ilmn-dev
        ica_workflow_id: wfl.94e76307ae1842c3b436c1209b7a865b
        versions:
          - name: 1.1.0--120
            path: 1.1.0--120/tso500-ctdna-reporting-workflow__1.1.0--120.cwl
            ica_workflow_version_name: 1.1.0--120
            modification_time: 2021-06-29T04:56:07UTC
            run_instances: []
      - name: custom-create-directory
        path: custom-create-directory
        ica_workflow_name: custom-create-directory_clb-ilmn-dev_wf
        ica_workflow_id: wfl.261e0e22cfc842579d708d7a14134d4b
        versions:
          - name: 1.0.0
            path: 1.0.0/custom-create-directory__1.0.0.cwl
            ica_workflow_version_name: 1.0.0
            modification_time: 2021-06-30T07:00:10UTC
            run_instances: []
    workflows:
      - name: tso500-ctdna
        path: tso500-ctdna
        ica_workflow_name: tso500-ctdna_clb-ilmn-dev
        ica_workflow_id: wfl.2f5f214de24b450c8c71a3f7d5c0ae16
        versions:
          - name: 1.1.0--120
            path: 1.1.0--120/tso500-ctdna__1.1.0--120.cwl
            ica_workflow_version_name: 1.1.0--120
            modification_time: 2021-06-29T04:56:07UTC
            run_instances: []
