schemas:
  - name: fastq-list-row
    path: fastq-list-row
    versions:
      - name: 1.0.0
        path: 1.0.0/fastq-list-row__1.0.0.yaml
        md5sum: 13ba7474e7bce7e5b1c49256634682b5
    categories: []
  - name: contig
    path: contig
    versions:
      - name: 1.0.0
        path: 1.0.0/contig__1.0.0.yaml
        md5sum: 4584d6b2739f4d02b934eead6fd1e328
    categories: []
  - name: predefined-mount-path
    path: predefined-mount-path
    versions:
      - name: 1.0.0
        path: 1.0.0/predefined-mount-path__1.0.0.yaml
        md5sum: da24a7c18dc1531382032a84fcaee2eb
    categories: []
  - name: tso500-sample
    path: tso500-sample
    versions:
      - name: 1.0.0
        path: 1.0.0/tso500-sample__1.0.0.yaml
        md5sum: 8c1b912aba28ab93bdce4f420f346380
    categories: []
