tools:
  - name: samtools-merge
    path: samtools-merge
    versions:
      - name: 1.12.0
        path: 1.12.0/samtools-merge__1.12.0.cwl
        md5sum: c45cb7a5439a5c1e438f8d81ec042939
    categories:
      - bam handlers
  - name: tabix
    path: tabix
    versions:
      - name: 0.2.6
        path: 0.2.6/tabix__0.2.6.cwl
        md5sum: 916ce72cb0d5275272e5356446b1c350
    categories: []
  - name: sambamba-merge-and-index
    path: sambamba-merge-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-merge-and-index__0.8.0.cwl
        md5sum: 1cdd2a6daff8b7fb232d08b915293d79
    categories: []
  - name: sambamba-sort-and-index
    path: sambamba-sort-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-sort-and-index__0.8.0.cwl
        md5sum: 1a6a0ac845bfffcfb32242f7388315be
    categories:
      - bam handler
  - name: sambamba-slice-and-index
    path: sambamba-slice-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-slice-and-index__0.8.0.cwl
        md5sum: 85cb186f34a4c635c6a3ed9f5e1dc701
    categories:
      - bam handler
  - name: sambamba-view-and-index
    path: sambamba-view-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-view-and-index__0.8.0.cwl
        md5sum: 5e4f3c81211efefcf6bc23fb59bb2ab1
    categories:
      - bam handler
  - name: optitype
    path: optitype
    versions:
      - name: 1.3.5
        path: 1.3.5/optitype__1.3.5.cwl
        md5sum: c48f5ee0ce0017eaeb12f2d1f0de1c62
    categories:
      - hla
  - name: custom-subset-bam
    path: custom-subset-bam
    versions:
      - name: 1.12.0
        path: 1.12.0/custom-subset-bam__1.12.0.cwl
        md5sum: beccb4a5e29eed5de0be6dc7617f3602
    categories:
      - bam handler
  - name: custom-hla-bed-from-faidx
    path: custom-hla-bed-from-faidx
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-hla-bed-from-faidx__1.0.0.cwl
        md5sum: ef945ce5417bc7886b3aa67dcb42977b
    categories: []
  - name: bedops
    path: bedops
    versions:
      - name: 2.4.39
        path: 2.4.39/bedops__2.4.39.cwl
        md5sum: 94cac9220b0156075600bc0a26a0c4b9
    categories: []
  - name: dragen-germline
    path: dragen-germline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-germline__3.7.5.cwl
        md5sum: 7ddc21a4ca6a8c0279061849a317cae1
    categories: []
  - name: custom-create-tso500-samplesheet
    path: custom-create-tso500-samplesheet
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-create-tso500-samplesheet__1.0.0.cwl
        md5sum: 16fc41821d43459286a47af79066447f
    categories:
      - tso500
  - name: tso500-ctdna-demultiplex-workflow
    path: tso500-ctdna-demultiplex-workflow
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna-demultiplex-workflow__1.1.0--120.cwl
        md5sum: 845748c4e1bf7064e615b3cee6882401
    categories:
      - tso500
  - name: tso500-ctdna-analysis-workflow
    path: tso500-ctdna-analysis-workflow
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna-analysis-workflow__1.1.0--120.cwl
        md5sum: b4490d13b1d0e8f0f6a48f4dd35325bb
    categories:
      - tso500
  - name: tso500-ctdna-reporting-workflow
    path: tso500-ctdna-reporting-workflow
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna-reporting-workflow__1.1.0--120.cwl
        md5sum: ab0e1bc6b5b7a8905257da439d1b2c97
    categories:
      - tso500
