tools:
  - name: samtools-merge
    path: samtools-merge
    versions:
      - name: 1.12.0
        path: 1.12.0/samtools-merge__1.12.0.cwl
        md5sum: c45cb7a5439a5c1e438f8d81ec042939
    categories:
      - bam handlers
  - name: tabix
    path: tabix
    versions:
      - name: 0.2.6
        path: 0.2.6/tabix__0.2.6.cwl
        md5sum: 916ce72cb0d5275272e5356446b1c350
    categories: []
  - name: sambamba-merge-and-index
    path: sambamba-merge-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-merge-and-index__0.8.0.cwl
        md5sum: 1cdd2a6daff8b7fb232d08b915293d79
    categories: []
  - name: sambamba-sort-and-index
    path: sambamba-sort-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-sort-and-index__0.8.0.cwl
        md5sum: 1a6a0ac845bfffcfb32242f7388315be
    categories:
      - bam handler
  - name: sambamba-slice-and-index
    path: sambamba-slice-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-slice-and-index__0.8.0.cwl
        md5sum: 85cb186f34a4c635c6a3ed9f5e1dc701
    categories:
      - bam handler
  - name: sambamba-view-and-index
    path: sambamba-view-and-index
    versions:
      - name: 0.8.0
        path: 0.8.0/sambamba-view-and-index__0.8.0.cwl
        md5sum: 5e4f3c81211efefcf6bc23fb59bb2ab1
    categories:
      - bam handler
  - name: optitype
    path: optitype
    versions:
      - name: 1.3.5
        path: 1.3.5/optitype__1.3.5.cwl
        md5sum: c48f5ee0ce0017eaeb12f2d1f0de1c62
    categories:
      - hla
  - name: custom-subset-bam
    path: custom-subset-bam
    versions:
      - name: 1.12.0
        path: 1.12.0/custom-subset-bam__1.12.0.cwl
        md5sum: beccb4a5e29eed5de0be6dc7617f3602
    categories:
      - bam handler
  - name: custom-hla-bed-from-faidx
    path: custom-hla-bed-from-faidx
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-hla-bed-from-faidx__1.0.0.cwl
        md5sum: 34b3939fbdb3d642e299b3662151d284
    categories: []
  - name: bedops
    path: bedops
    versions:
      - name: 2.4.39
        path: 2.4.39/bedops__2.4.39.cwl
        md5sum: 94cac9220b0156075600bc0a26a0c4b9
    categories: []
  - name: dragen-germline
    path: dragen-germline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-germline__3.7.5.cwl
        md5sum: 54dd1c2214ab62a252ba9fb195af749d
    categories: []
  - name: custom-create-tso500-samplesheet
    path: custom-create-tso500-samplesheet
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-create-tso500-samplesheet__1.0.0.cwl
        md5sum: 29de97b423f0c16bc3b0200e4449a51f
    categories:
      - tso500
  - name: tso500-ctdna-demultiplex-workflow
    path: tso500-ctdna-demultiplex-workflow
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna-demultiplex-workflow__1.1.0--120.cwl
        md5sum: 64829a605ed798458fbe4772c8970248
    categories:
      - tso500
  - name: tso500-ctdna-analysis-workflow
    path: tso500-ctdna-analysis-workflow
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna-analysis-workflow__1.1.0--120.cwl
        md5sum: 26f06d67bc0c1b8569f4d03d91335b44
    categories:
      - tso500
  - name: tso500-ctdna-reporting-workflow
    path: tso500-ctdna-reporting-workflow
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna-reporting-workflow__1.1.0--120.cwl
        md5sum: 63a3b446bbcde4bd82a1c3b00b8d623a
    categories:
      - tso500
  - name: custom-samplesheet-split-by-settings
    path: custom-samplesheet-split-by-settings
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-samplesheet-split-by-settings__1.0.0.cwl
        md5sum: 4dd3425af669e23740532a838748f9d8
    categories: []
  - name: bclConvert
    path: bclConvert
    versions:
      - name: 3.7.5
        path: 3.7.5/bclConvert__3.7.5.cwl
        md5sum: 974f3efc9ceb0134dc8e6a3177bc2e6d
    categories: []
  - name: create-dummy-file
    path: create-dummy-file
    versions:
      - name: 1.0.0
        path: 1.0.0/create-dummy-file__1.0.0.cwl
        md5sum: e3489c0a1a03c088ce4b0865105b348d
    categories: []
  - name: multiqc-interop
    path: multiqc-interop
    versions:
      - name: 1.2.1
        path: 1.2.1/multiqc-interop__1.2.1.cwl
        md5sum: 346fde115ccefa53c32b28be0c9978ff
    categories: []
  - name: dragen-somatic
    path: dragen-somatic
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-somatic__3.7.5.cwl
        md5sum: 476ffd3dba9f93e6aeea222d45d373cd
    categories: []
  - name: dragen-transcriptome
    path: dragen-transcriptome
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-transcriptome__3.7.5.cwl
        md5sum: 3e8892098f60deddb31706161f95893f
    categories: []
  - name: arriba-fusion-calling
    path: arriba-fusion-calling
    versions:
      - name: 2.0.0
        path: 2.0.0/arriba-fusion-calling__2.0.0.cwl
        md5sum: 69aa192fdf98f2ad3356e37a3fda5519
    categories: []
  - name: arriba-drawing
    path: arriba-drawing
    versions:
      - name: 2.0.0
        path: 2.0.0/arriba-drawing__2.0.0.cwl
        md5sum: 87ee5552c7c0e3aad1a74d5b3a75dc4b
    categories: []
  - name: multiqc
    path: multiqc
    versions:
      - name: 1.10.1
        path: 1.10.1/multiqc__1.10.1.cwl
        md5sum: 41ed548ff78108ac73741fd6cdc6ea6c
      - name: 1.11.0
        path: 1.11.0/multiqc__1.11.0.cwl
        md5sum: 59614d4be56c46d9ac9d31bcef91eff8
    categories:
      - qc
      - visual
  - name: dragen-alignment
    path: dragen-alignment
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-alignment__3.7.5.cwl
        md5sum: b6b90c6e5016c4718c73813b10699a32
    categories: []
  - name: custom-create-directory
    path: custom-create-directory
    versions:
      - name: 1.0.0
        path: 1.0.0/custom-create-directory__1.0.0.cwl
        md5sum: be103cf071c9e7abfcd5afae7ca2f821
    categories: []
  - name: dragen-build-reference-tarball
    path: dragen-build-reference-tarball
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-build-reference-tarball__3.7.5.cwl
        md5sum: 6125bf3e82c9bc95b6cee76a7cb11b27
    categories: []
