workflows:
  - name: optitype-pipeline
    path: optitype-pipeline
    versions:
      - name: 1.3.5
        path: 1.3.5/optitype-pipeline__1.3.5.cwl
        md5sum: a6cafecc661f1c43f1f928d42218ddf4
    categories:
      - hla
  - name: get-hla-regions-bed
    path: get-hla-regions-bed
    versions:
      - name: 1.0.0
        path: 1.0.0/get-hla-regions-bed__1.0.0.cwl
        md5sum: 8c0f5b8d32082d3ae4a348ca97240d35
    categories: []
  - name: dragen-germline-pipeline
    path: dragen-germline-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-germline-pipeline__3.7.5.cwl
        md5sum: 74908639306d9d2441ae21e396c85871
    categories: []
  - name: dragen-qc-hla-pipeline
    path: dragen-qc-hla-pipeline
    versions:
      - name: 3.7.5--1.3.5
        path: 3.7.5--1.3.5/dragen-qc-hla-pipeline__3.7.5--1.3.5.cwl
        md5sum: d18cc615447cfb2e1fa75364a80bc335
    categories: []
  - name: tso500-ctdna
    path: tso500-ctdna
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna__1.1.0--120.cwl
        md5sum: bb4a12084822bed9c7dd1cbed8b0173e
    categories:
      - tso500
  - name: bcl-conversion
    path: bcl-conversion
    versions:
      - name: 3.7.5
        path: 3.7.5/bcl-conversion__3.7.5.cwl
        md5sum: 037e133e04d5f527208a20e1246dace4
    categories: []
  - name: dragen-somatic
    path: dragen-somatic
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-somatic__3.7.5.cwl
        md5sum: d1c1ed2c2cea5325c11c160728b5d204
    categories: []
