workflows:
  - name: optitype-pipeline
    path: optitype-pipeline
    versions:
      - name: 1.3.5
        path: 1.3.5/optitype-pipeline__1.3.5.cwl
        md5sum: a6cafecc661f1c43f1f928d42218ddf4
    categories:
      - hla
  - name: get-hla-regions-bed
    path: get-hla-regions-bed
    versions:
      - name: 1.0.0
        path: 1.0.0/get-hla-regions-bed__1.0.0.cwl
        md5sum: 8c0f5b8d32082d3ae4a348ca97240d35
    categories: []
  - name: dragen-germline-pipeline
    path: dragen-germline-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-germline-pipeline__3.7.5.cwl
        md5sum: 8d822eb3fa5c2c5196bd291b869d1e39
    categories: []
  - name: dragen-qc-hla-pipeline
    path: dragen-qc-hla-pipeline
    versions:
      - name: 3.7.5--1.3.5
        path: 3.7.5--1.3.5/dragen-qc-hla-pipeline__3.7.5--1.3.5.cwl
        md5sum: e98361e2ac1f26836f8f257a5db3053e
    categories: []
  - name: tso500-ctdna
    path: tso500-ctdna
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna__1.1.0--120.cwl
        md5sum: bb4a12084822bed9c7dd1cbed8b0173e
    categories:
      - tso500
  - name: bcl-conversion
    path: bcl-conversion
    versions:
      - name: 3.7.5
        path: 3.7.5/bcl-conversion__3.7.5.cwl
        md5sum: 5bf579de1c6822b41e8f525cfbd85421
    categories: []
  - name: dragen-somatic
    path: dragen-somatic
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-somatic__3.7.5.cwl
        md5sum: 6c27a4a1e3dc1e7999d90d46f796a27f
    categories: []
  - name: dragen-transcriptome-pipeline
    path: dragen-transcriptome-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-transcriptome-pipeline__3.7.5.cwl
        md5sum: 3470e5804826c5affbf5fa18ec1664d2
    categories: []
