workflows:
  - name: optitype-pipeline
    path: optitype-pipeline
    versions:
      - name: 1.3.5
        path: 1.3.5/optitype-pipeline__1.3.5.cwl
        md5sum: 8a60ddcaa75b85884785de055320280f
    categories:
      - hla
  - name: get-hla-regions-bed
    path: get-hla-regions-bed
    versions:
      - name: 1.0.0
        path: 1.0.0/get-hla-regions-bed__1.0.0.cwl
        md5sum: fde83608bc8d0624b260cc2fb9609420
    categories: []
  - name: dragen-germline-pipeline
    path: dragen-germline-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-germline-pipeline__3.7.5.cwl
        md5sum: 9c415babb9da86131c01d4e816d9ef67
    categories:
      - dragen
  - name: dragen-qc-hla-pipeline
    path: dragen-qc-hla-pipeline
    versions:
      - name: 3.7.5--1.3.5
        path: 3.7.5--1.3.5/dragen-qc-hla-pipeline__3.7.5--1.3.5.cwl
        md5sum: 5380314a8aec7e17de1f2be6ce95e75b
    categories: []
  - name: tso500-ctdna
    path: tso500-ctdna
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna__1.1.0--120.cwl
        md5sum: 49a75e54a74e3b7920c972bec4d42bfb
    categories:
      - tso500
  - name: bcl-conversion
    path: bcl-conversion
    versions:
      - name: 3.7.5
        path: 3.7.5/bcl-conversion__3.7.5.cwl
        md5sum: b2706702f99a6b3d934b4e667f7a4eb7
    categories: []
  - name: dragen-somatic-pipeline
    path: dragen-somatic-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-somatic-pipeline__3.7.5.cwl
        md5sum: 605e6e7e39454132389ab3ec24437371
    categories:
      - dragen
      - variant-calling
  - name: dragen-transcriptome-pipeline
    path: dragen-transcriptome-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-transcriptome-pipeline__3.7.5.cwl
        md5sum: 88f0ca8072c64375838c643ea3b4113c
      - name: 3.8.4
        path: 3.8.4/dragen-transcriptome-pipeline__3.8.4.cwl
        md5sum: e8e6460cde1c163319a6f2e20ff1d2f7
    categories: []
  - name: dragen-alignment-pipeline
    path: dragen-alignment-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-alignment-pipeline__3.7.5.cwl
        md5sum: 7d1f53b5a952427be5dbcd1165795907
    categories:
      - alignment
      - dragen
  - name: dragen-wgs-qc-pipeline
    path: dragen-wgs-qc-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-wgs-qc-pipeline__3.7.5.cwl
        md5sum: e8a5f7e0631cb9d14303f56d67e408d7
    categories:
      - dragen
  - name: tso500-ctdna-post-processing-pipeline
    path: tso500-ctdna-post-processing-pipeline
    versions:
      - name: 1.0.0
        path: 1.0.0/tso500-ctdna-post-processing-pipeline__1.0.0.cwl
        md5sum: b0a72afc88786e8e0bf4099d2859bdfd
    categories:
      - tso500
  - name: umccrise-pipeline
    path: umccrise-pipeline
    versions:
      - name: 1.2.1--0
        path: 1.2.1--0/umccrise-pipeline__1.2.1--0.cwl
        md5sum: 6100f32cc0c1ecf82da6ea0da96f8622
      - name: 1.2.2--0
        path: 1.2.2--0/umccrise-pipeline__1.2.2--0.cwl
        md5sum: 54fb347935cbbf36c5a36b7e4df6240d
    categories: []
  - name: tso500-ctdna-with-post-processing-pipeline
    path: tso500-ctdna-with-post-processing-pipeline
    versions:
      - name: 1.1.0--1.0.0
        path: 1.1.0--1.0.0/tso500-ctdna-with-post-processing-pipeline__1.1.0--1.0.0.cwl
        md5sum: 8b6c10d7e232b1a5b932d5038ad50ce7
    categories:
      - tso500
  - name: umccrise-pipeline
    path: umccrise-pipeline
    versions:
      - name: 1.2.1--0
        path: 1.2.1--0/umccrise-pipeline__1.2.1--0.cwl
        md5sum: 6100f32cc0c1ecf82da6ea0da96f8622
      - name: 1.2.2--0
        path: 1.2.2--0/umccrise-pipeline__1.2.2--0.cwl
        md5sum: 54fb347935cbbf36c5a36b7e4df6240d
    categories: []
