workflows:
  - name: optitype-pipeline
    path: optitype-pipeline
    versions:
      - name: 1.3.5
        path: 1.3.5/optitype-pipeline__1.3.5.cwl
        md5sum: 8a60ddcaa75b85884785de055320280f
    categories:
      - hla
  - name: get-hla-regions-bed
    path: get-hla-regions-bed
    versions:
      - name: 1.0.0
        path: 1.0.0/get-hla-regions-bed__1.0.0.cwl
        md5sum: fde83608bc8d0624b260cc2fb9609420
    categories: []
  - name: dragen-germline-pipeline
    path: dragen-germline-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-germline-pipeline__3.7.5.cwl
        md5sum: 9c415babb9da86131c01d4e816d9ef67
    categories:
      - dragen
  - name: dragen-qc-hla-pipeline
    path: dragen-qc-hla-pipeline
    versions:
      - name: 3.7.5--1.3.5
        path: 3.7.5--1.3.5/dragen-qc-hla-pipeline__3.7.5--1.3.5.cwl
        md5sum: 5380314a8aec7e17de1f2be6ce95e75b
    categories: []
  - name: tso500-ctdna
    path: tso500-ctdna
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna__1.1.0--120.cwl
        md5sum: ec548f9429f4df6619b30569f498bf5b
    categories:
      - tso500
  - name: bcl-conversion
    path: bcl-conversion
    versions:
      - name: 3.7.5
        path: 3.7.5/bcl-conversion__3.7.5.cwl
        md5sum: b2706702f99a6b3d934b4e667f7a4eb7
    categories: []
  - name: dragen-somatic-pipeline
    path: dragen-somatic-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-somatic-pipeline__3.7.5.cwl
        md5sum: 1e102e38c9fcdbbbe41f9a013f3ceb61
    categories:
      - dragen
      - variant-calling
  - name: dragen-transcriptome-pipeline
    path: dragen-transcriptome-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-transcriptome-pipeline__3.7.5.cwl
        md5sum: 083dfb1e079d1eaec037ceba7dae802c
    categories: []
  - name: dragen-alignment-pipeline
    path: dragen-alignment-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-alignment-pipeline__3.7.5.cwl
        md5sum: 7d1f53b5a952427be5dbcd1165795907
    categories:
      - alignment
      - dragen
  - name: dragen-wgs-qc-pipeline
    path: dragen-wgs-qc-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-wgs-qc-pipeline__3.7.5.cwl
        md5sum: e8a5f7e0631cb9d14303f56d67e408d7
    categories:
      - dragen
