name: create catalogue

on:
  workflow_run:
    workflows: ["Sync tools and sync workflows"]
    branches:
     - beta-release  # TODO move to 'main'
    paths:
      # Workflow change
      - "**/*.cwl"
      # GH change
      - ".github/workflows/create_catalogue.yml"
      - ".github/actions/create_catalogue/action.yml"
      - ".github/scripts/create_catalogue.sh"
      - "src/install.sh"
      # Config files (say a merge conflict is resolved)
      - "config/project.yaml"
      - "config.tool.yaml"
      - "config/workflow.yaml"
      - "config/expression.yaml"
      - "config/run.yaml"
      - "config/categories.yaml"

jobs:
  create_catalogue:
    name: create catalogue
    concurrency: git_commits  # Although runs only after sync tools, could run in parallel to update auto completion?
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.CREATE_CATALOGUE_SSHKEY }}"
      # Create container with user
      - name: Create container with user added
        run: |
          docker run --name anaconda3_with_user \
            continuumio/anaconda3:2021.05 \
              sh -c "export DEBIAN_FRONTEND=noninteractive && \
                     echo 'Updating Apt' 1>&2 && \
                     apt-get update -y -q && \
                     echo 'Installing jq, nodejs, rsync, graphviz and parallel' 1>&2 && \
                     apt-get install -y -q \
                       jq \
                       nodejs \
                       rsync \
                       graphviz \
                       parallel && \
                     echo 'Cleaning up after apt installations' 1>&2 && \
                     apt-get clean -y && \
                     echo 'Installing yq' 1>&2 && \
                     wget https://github.com/mikefarah/yq/releases/download/v4.11.2/yq_linux_amd64 \
                         --output-document /usr/bin/yq && \
                     chmod +x /usr/bin/yq
                     echo 'Adding user groups' 1>&2 && \
                     addgroup \
                       --gid \"$(id -g)\" \
                       \"$(id -ng)\" && \
                     adduser \
                       --disabled-password \
                       --gid \"$(id -g)\" \
                       --uid \"$(id -u)\" \"$(id -nu)\""
      - name: Commit Container to image
        run: |
          docker commit anaconda3_with_user continuumio/anaconda3:2021.05-user
      # Create Catalogue
      - name: create catalogue
        run: |
          docker run \
            --rm \
            --user "$(id -u):$(id -g)" \
            --volume  "$PWD:$PWD" \
            --workdir "$PWD" \
            --env USER="$(id -nu)" \
            --env GITHUB_SERVER_URL="${GITHUB_SERVER_URL}" \
            --env GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" \
            continuumio/anaconda3:2021.05-user \
              sh -c "conda config --append pkgs_dirs \"\$HOME/.conda/pkgs\" && \
                     conda config --append envs_dirs \"\$HOME/.conda/envs\" && \
                     bash \".github/scripts/create_catalogue.sh\""
      # Commit catalogue file
      - name: Commit catalogue files
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "[ 'cwl-ica-catalogue.md', '.github/catalogue/' ]"
          author_name: "auto-catalogue-updater"
          message: "Updating cwl ica catalogue files - (Autogenerated github actions commit)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Push config files
      - name: Push code
        id: git_push
        run: |
          # Pull first
          git pull --rebase origin "${GITHUB_REF}"

          # Push after
          git push origin "${GITHUB_REF}"