name: Sync tools and sync workflows

on:
  push:
   branches:
    - beta-release  # To be moved to 'main'
   paths:
     # Workflow change
     - "**/*.cwl"
     # GH change
     - ".github/workflows/sync-tools_and_sync-workflows.yml"
     - ".github/actions/sync-tools_and_sync-workflows/action.yml"
     - ".github/scripts/run_sync-tools_and_sync-workflows.sh"
     - "src/install.sh"

jobs:
  sync_tools_and_workflows:
    name: sync-tools and sync-workflows
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v2
      # Get git commit ID
      - name: Get git commit ID
        id: get_git_commit_id
        run: echo "::set-output name=git_commit_id::$(git log --format="%H" -n1 | cut -c1-7)"
      # Create container with user
      - name: Create container with user added
        run: |
          docker run --name anaconda3_with_user \
            continuumio/anaconda3:2021.05 \
              sh -c "export DEBIAN_FRONTEND=noninteractive && \
                     apt-get update -y -q && \
                     apt-get install -y -q \
                       jq \
                       nodejs \
                       rsync && \
                     apt-get clean -y && \
                     addgroup \
                       --gid \"$(id -g)\" \
                       \"$(id -ng)\" && \
                     adduser \
                       --disabled-password \
                       --gid \"$(id -g)\" \
                       --uid \"$(id -u)\" \"$(id -nu)\""
      - name: Commit Container to image
        run: |
          docker commit anaconda3_with_user continuumio/anaconda3:2021.05-user
      # Sync tools and workflows
      - name: sync-tools and sync-workflows
        run: |
          docker run \
            --rm \
            --user "$(id -u):$(id -g)" \
            --volume  "$PWD:$PWD" \
            --workdir "$PWD" \
            --env USER="$(id -nu)" \
            continuumio/anaconda3:2021.05-user \
              sh -c "conda config --append pkgs_dirs \"\$HOME/.conda/pkgs\" && \
                     conda config --append envs_dirs \"\$HOME/.conda/envs\" && \
                     bash \".github/scripts/run_sync-tools_and_sync-workflows.sh\" \
                       '${{ steps.get_git_commit_id.outputs.git_commit_id }}' \
                       '${{ secrets.ICA_ACCESS_TOKENS_JSON }}'"
      # Commit to github
      - name: Commit configuration yaml files
        uses: EndBug/add-and-commit@v4
        with:
          add: "config/"
          author_name: "auto-config-updater"
          message: "Updating config - (Autogenerated github actions commit)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          branch: beta-release  # To be moved to 'main'