name: Sync tools and sync workflows and create catalogue

on:
  pull_request_review:
    types:
      - "submitted"
    branches:
     - main
    paths:
      # Workflow change
      - "**/*.cwl"
      # GH change
      - ".github/workflows/sync-tools_and_sync-workflows.yml"
      - ".github/scripts/run_sync-tools_and_sync-workflows.sh"
      # Also for changes in the catalogue script
      - ".github/create_catalogue.sh"
      - "src/install.sh"
      # Config files (say a merge conflict is resolved)
      - "config/project.yaml"
      - "config.tool.yaml"
      - "config/workflow.yaml"
      - "config/run.yaml"
      # Also for catalogue creation script changes
      - "src/subcommands/github_actions/create_catalogue.py"
      - "src/subcommands/github_actions/create_markdown_file.py"
      - "src/subcommands/sync/sync_github_actions.py"

jobs:
  sync_tools_and_workflows_and_create_catalogue:
    if: github.event.review.state == 'approved'
    name: sync-tools and sync-workflows and create-catalogue
    concurrency: git_commits
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v2
      # Get git commit ID
      - name: Get git commit ID
        id: get_git_commit_id
        run: echo "::set-output name=git_commit_id::$(git log --format="%H" -n1 | cut -c1-7)"
      # Create container with user
      - name: Create container with user added
        run: |
          docker run --name anaconda3_with_user \
            continuumio/anaconda3:2021.05 \
              sh -c "export DEBIAN_FRONTEND=noninteractive && \
                     echo 'Updating Apt' 1>&2 && \
                     apt-get update -y -q && \
                     echo 'Installing jq, nodejs, rsync, graphviz and parallel' 1>&2 && \
                     apt-get install -y -q \
                       jq \
                       nodejs \
                       rsync \
                       graphviz \
                       parallel && \
                     echo 'Cleaning up after apt installations' 1>&2 && \
                     apt-get clean -y && \
                     echo 'Installing yq' 1>&2 && \
                     wget https://github.com/mikefarah/yq/releases/download/v4.11.2/yq_linux_amd64 \
                         --output-document /usr/bin/yq && \
                     chmod +x /usr/bin/yq && \
                     echo 'Adding user groups' 1>&2 && \
                     addgroup \
                       --gid \"$(id -g)\" \
                       \"$(id -ng)\" && \
                     adduser \
                       --disabled-password \
                       --gid \"$(id -g)\" \
                       --uid \"$(id -u)\" \"$(id -nu)\""
      - name: Commit Container to image
        run: |
          docker commit anaconda3_with_user continuumio/anaconda3:2021.05-user
      # Sync tools and workflows
      - name: sync-tools and sync-workflows
        run: |
          docker run \
            --rm \
            --user "$(id -u):$(id -g)" \
            --volume  "$PWD:$PWD" \
            --workdir "$PWD" \
            --env USER="$(id -nu)" \
            --env GIT_COMMIT_ID="${{ steps.get_git_commit_id.outputs.git_commit_id }}" \
            --env SECRETS_JSON="${{ secrets.ICA_ACCESS_TOKENS_JSON }}" \
            --env ICA_BASE_URL="${{ secrets.ICA_BASE_URL }}" \
            continuumio/anaconda3:2021.05-user \
              sh -c "conda config --append pkgs_dirs \"\$HOME/.conda/pkgs\" && \
                     conda config --append envs_dirs \"\$HOME/.conda/envs\" && \
                     bash \".github/scripts/run_sync-tools_and_sync-workflows.sh\""
      # Create Catalogue
      - name: create catalogue
        run: |
          docker run \
            --rm \
            --user "$(id -u):$(id -g)" \
            --volume  "$PWD:$PWD" \
            --workdir "$PWD" \
            --env USER="$(id -nu)" \
            --env GITHUB_SERVER_URL="${GITHUB_SERVER_URL}" \
            --env GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" \
            continuumio/anaconda3:2021.05-user \
              sh -c "conda config --append pkgs_dirs \"\$HOME/.conda/pkgs\" && \
                     conda config --append envs_dirs \"\$HOME/.conda/envs\" && \
                     bash \".github/scripts/create_catalogue.sh\""
      # Commit config files
      - name: Commit catalogue files
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: "[ 'config/', 'cwl-ica-catalogue.md', '.github/catalogue/' ]"
          author_name: "auto-catalogue-updater"
          message: "Updating cwl ica config and catalogue files - (Autogenerated github actions commit)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Push config files
      - name: Push code
        id: git_push
        run: |
          # Pull first
          git pull --rebase origin "${GITHUB_REF}"

          # Push after
          git push origin "${GITHUB_REF}"